# Generated by Django 5.0.6 on 2024-06-07 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0017_ordersave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersave',
            options={'verbose_name': 'buyurtma', 'verbose_name_plural': 'buyurtmalar'},
        ),
        migrations.RemoveField(
            model_name='ordersave',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ordersave',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='ordersave',
            name='user',
        ),
        migrations.AddField(
            model_name='ordersave',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileapp.address'),
        ),
        migrations.AddField(
            model_name='ordersave',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profileapp.clientprofile', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='new', max_length=50),
        ),
    ]
